### PR TITLE
wip: Working dev build with FuseBox v4

### PR DESCRIPTION
**Pull request by nchanged**
Hey @sentialx 

Here is a working dev build with FuseBox v4. There are a few issue to fix, but it has loaded correctly (nonetheless)

* Figure out the error `SyntaxError: Unexpected token < in JSON at position 0", source: devtools://devtools/bundled/shell.js` in the terminal.
* Remove webpack specific things (I believe there is something left
* Figure out why wexond-darkreader won't work

I advise you using dynamic imports, as in
```
await import("./some-extension")
```

v4 supports code splitting out of the box

* Make sure production build is properly working.
* Fixed on fuse side that warning (it spits out a warning that console isn't found) I will take care of that. 

Let's make it work, please let me know what you think. 

P.S while configuring make sure the cache is disabled. With cache it will take 50ms to reload the app.

### CODE REVIEW

**Comment by sentialx** [comment]
Hi, thank you for your PR, I appreciate that! However Wexond has also multiple dialogs (i.e. permissions, auth) which are separate renderer processes and they need to have separate entries. It would be also great if they had shared vendor bundle with React, styled-components etc. to reduce bundle size. Is it possible to do?

**Comment by kierandrewett** [comment]
This looks awesome @nchanged! This is going to help Sential and me so much.

**Comment by sentialx** [comment]
@nchanged Also, in the 4.0.0 update the settings, history etc. applets will be separated to web pages (which don't have Electron APIs) , so I will need to do something similar to this: https://github.com/wexond/desktop/blob/4.0.0/webpack.config.renderer.js#L94

**Comment by nchanged** [comment]
@sentialx it's possible of course!  Are we talking about different mains or different renderers? If it's different renderers that's very very easy with `import`

`await import ("./some-other-rendeere")`

v4 will split it into a separate bundle respecting parent vendors and taking unique ones along with it **during production**. We can try working on it together. If you fix the very essentials (there are still a few issues there)

**Comment by nchanged** [comment]
@sentialx instead of making it in the config, it's better to create a file `entry.ts` and start with it

e.g.

```
import "./app"
import "./permissions"
```

That will make it bundler agnostic and reduce the complexity of your configuration

**Comment by sentialx** [comment]
@nchanged Will it also create HTML web pages to be able to load them in separate Electron BrowserWindows?

**Comment by nchanged** [comment]
could you gimme an example? So you want to open a separate html file with preloaded bundles? If so, we could cook a plugin for that. That's not a straight forward task to have it implemented in the core

**Comment by sentialx** [comment]
I would like to have following structure (which I achieved with webpack):
- `vendor.electron.bundle.js` (vendor for target: `electron`)
- `vendor.web.bundle.js` (vendor for target: `web`)
- `app.html` (the browser UI, target: `electron`)
  - `app.bundle.js`
- `permissions.html` (target: `electron`)
  - `permissions.bundle.js`
- `history.html` (target: `web`)
  - `history.bundle.js`

The `permissions` dialog looks like this:
image

**Comment by nchanged** [comment]
@sentialx could you show an example of how you're using it? 
I assume the html contains contains vendor too? I think we can bypass this extra html and have one flow of modules (which is much easier)

**Comment by sentialx** [comment]
For example the `permissions.html` file looks like this:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Wexond</title>
  </head>

  <body>
    <div id="app"></div>
    <script type="text/javascript" src="vendor.electron.bundle.js"></script>
    <script type="text/javascript" src="permissions.bundle.js"></script>
  </body>
</html>
```

**Comment by sentialx** [comment]
And I load the HTML file in a new `BrowserWindow` like this: https://github.com/wexond/desktop/blob/master/src/main/windows/popup.ts#L29

**Comment by nchanged** [comment]
I will make a plugin for that, we will still use `import()` syntax for natural code splitting, We just need to generate a different index with different entries. That's not so hard. In the mean time, please make sure the the rest of the app is working fine

**Comment by nchanged** [comment]
I am introducing pluginSplitEntry

```
pluginSplitEntry({
     entries: ['src/split1', 'sec/split2'], // those will be resolved with a resolver.
})
```
Basically that will create split bundles, respecting shared vendors and shared modules as well. Hooking it up to webIndex won't be a big deal

**Comment by sentialx** [comment]
Closing due to inactivity

**Pull request closed without merging**
