### PR TITLE
feat: support mouse forward/backward buttons

### PR DESCRIPTION
**Pull request by 0x6A6F73**
A small addition to support navigation with the forward and backward buttons on mice and other hardware using the [Electron 'app-command' event](https://www.electronjs.org/docs/api/browser-window#event-app-command-windows-linux).

### CODE REVIEW

**Comment by sentialx** [comment]
recheckcla

**Comment by sentialx** [comment]
**CLA Assistant Lite:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/wexond/desktop/blob/master/cla.md) before we can accept your contribution. You can sign the CLA by just  posting a Pull Request Comment same as the below format.
  - - -
  ***I have read the CLA Document and I hereby sign the CLA***
  - - - 
  <sub>You can retrigger the CLA Action by commenting **recheckcla** in this Pull Request</sub>

**Comment by sentialx** [comment]
Did you test that it works? Because last time I checked the `app-command` event didn't work, instead I did a workaround using event listener in the preload script.

**Comment by 0x6A6F73** [comment]
You're right, it seems to not work correctly. The preload script implementation wasn't working in the release I downloaded. When I tried adding the app-command to the code I mistakenly thought my code was working when it was actually yours 🙃 Sorry about that.

**Pull request closed without merging**
