### PR TITLE
fix: print menu button

### PR DESCRIPTION
**Pull request by manfromarce**
I noticed that the Print button in main menu does nothing, instead the context menu button works. This PR should fix the issue and also adds Print as PDF with default Electron options (marginsType: 0, printBackground: false, printSelectionOnly: false, landscape: false)

### CODE REVIEW

**Comment by sentialx** [comment]
We don't need a print to PDF option at this moment.

**Comment by sentialx** [comment]
@manfromarce You can remove the save to pdf option, I will solve it similarly as Chrome does it but later. But thanks for fixing the print button.

**Comment by manfromarce** [comment]
Ok, I removed the print to PDF option.

**Comment by sentialx** [comment]
recheckcla

**Comment by manfromarce** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
